<a href="https://www.kaggle.com/code/mrafraim/dl-day-7-mini-exercise?scriptVersionId=285889427" target="_blank"><img align="left" alt="Kaggle" title="Open in Kaggle" src="https://kaggle.com/static/images/open-in-kaggle.svg"></a>

# Day 7: Mini Exercise
Welcome to Day 7! 

Today you will:
- Manually compute the output of a neuron  
- Practice forward propagation calculations  
- Build small network experiments using NumPy  
- Strengthen your intuition of weights, bias, activation, and loss

Let’s begin!

---

# Exercise 1: Manual Neuron Output

Given:
- Input: $x = 3$
- Weight: $w = 0.7$
- Bias: $b = -1$
- Activation: ReLU

Step-by-step:

### 1. Weighted sum  
$$
z = w \cdot x + b
$$
$$
z = 0.7 \cdot 3 - 1 = 1.1
$$

### 2. Activation  
ReLU:
$$
ReLU(z) = \max(0, z)
$$

Final output:
$$
a = 1.1
$$


# Code for Exercise 1

In [1]:
x = 3
w = 0.7
b = -1

z = w * x + b
a = max(0, z)  # ReLU

print("z =", z)
print("Activated output =", a)

z = 1.0999999999999996
Activated output = 1.0999999999999996


# Exercise 2: Compute Prediction + Loss

Given:
- Input: $x = 2$
- Weight: $w = -0.4$
- Bias: $b = 0.2$
- Target: $y = 1$
- Activation: Sigmoid

### Step-1: Weighted sum
$$
z = w x + b
$$

### Step-2: Sigmoid activation
$$
\sigma(z) = \frac{1}{1 + e^{-z}}
$$

### Step-3: MSE loss
$$
L = (a - y)^2
$$


# Code for Exercise 2

In [2]:
import numpy as np

x = 2
w = -0.4
b = 0.2
y_true = 1

# Forward pass
z = w * x + b
a = 1 / (1 + np.exp(-z))  # Sigmoid
loss = (a - y_true)**2    # MSE

print("z =", z)
print("Sigmoid activation =", a)
print("Loss =", loss)


z = -0.6000000000000001
Sigmoid activation = 0.35434369377420455
Loss = 0.4168720657691381


# Exercise 3: Two Neuron Layer (Forward Prop)

We have a layer with **2 neurons**.

Inputs:
$$
x = \begin{bmatrix} 1 \\ 2 \end{bmatrix}
$$

Weights:
$$
W = \begin{bmatrix}
0.5 & -0.3 \\
0.8 & 0.1
\end{bmatrix}
$$

Bias:
$$
b = \begin{bmatrix}
0.0 \\
-0.2
\end{bmatrix}
$$

Activation: ReLU

### Step-1: Linear output
$$
z = W x + b
$$

### Step-2: ReLU activation
$$
a_i = \max(0, z_i)
$$


# Code for Exercise 3

In [3]:
import numpy as np

x = np.array([[1],
              [2]])

W = np.array([[0.5, -0.3],
              [0.8,  0.1]])

b = np.array([[ 0.0],
              [-0.2]])

z = np.dot(W, x) + b
a = np.maximum(0, z)

print("z:\n", z)
print("\nActivated output:\n", a)


z:
 [[-0.1]
 [ 0.8]]

Activated output:
 [[0. ]
 [0.8]]


# Exercise 4: Modify Weights, See Changes

Let’s observe how changing weights affects the output.

Try changing:
- Weight values  
- Bias  
- Activation (ReLU → Sigmoid)  

Questions to think about:
1. Does increasing weights make outputs larger?  
2. How does bias shift the output?  
3. How do different activations behave?


# Interactive Experiment Code

In [4]:
# Baseline
x = np.array([[1],
              [2]])

W = np.array([[0.5, -0.3],
              [0.8,  0.1]])

b = np.array([[ 0.0],
              [-0.2]])

# Forward pass
z = np.dot(W, x) + b
a_relu = np.maximum(0, z)
a_sigmoid = 1 / (1 + np.exp(-z))

print("z:\n", z)
print("\nReLU output:\n", a_relu)
print("\nSigmoid output:\n", a_sigmoid)

z:
 [[-0.1]
 [ 0.8]]

ReLU output:
 [[0. ]
 [0.8]]

Sigmoid output:
 [[0.47502081]
 [0.68997448]]


In [5]:
W = np.array([[1.0, -0.5],
              [0.7,  0.2]])  # weights changed

# Forward pass
z = np.dot(W, x) + b
a_relu = np.maximum(0, z)
a_sigmoid = 1 / (1 + np.exp(-z))

print("See the impact of changing only the weights:")
print("z:\n", z)
print("\nReLU output:\n", a_relu)
print("\nSigmoid output:\n", a_sigmoid)

See the impact of changing only the weights:
z:
 [[0. ]
 [0.9]]

ReLU output:
 [[0. ]
 [0.9]]

Sigmoid output:
 [[0.5      ]
 [0.7109495]]


### When we changed weights only

* Input stayed the same.
* Bias stayed the same.
* Result:
  (z) changed from

$$
\begin{bmatrix}
-0.1 \\
0.8
\end{bmatrix}
$$

$$to$$

$$
\begin{bmatrix}
0. \\
0.9
\end{bmatrix}
$$

**What this means:**
Weights decide how strongly inputs push the neuron up or down.
Change weights → the *direction and strength* of the push changes.

That’s why the second neuron’s output increased and the first moved closer to zero.

In [6]:
W = np.array([[0.5, -0.3],
              [0.8,  0.1]]) # Weights of baseline

b = np.array([[0.2],
              [-0.1]]) # Bias changed

# Forward pass
z = np.dot(W, x) + b
a_relu = np.maximum(0, z)
a_sigmoid = 1 / (1 + np.exp(-z))

print("See the impact of changing only the bias:")
print("z:\n", z)
print("\nReLU output:\n", a_relu)
print("\nSigmoid output:\n", a_sigmoid)

See the impact of changing only the bias:
z:
 [[0.1]
 [0.9]]

ReLU output:
 [[0.1]
 [0.9]]

Sigmoid output:
 [[0.52497919]
 [0.7109495 ]]


### When you changed **bias only**

* Input stayed the same.
* Weights stayed the same as baseline.
* Result:
  (z) changed from 

$$
\begin{bmatrix}
-0.1 \\
0.8
\end{bmatrix}
$$

$$to$$

$$
\begin{bmatrix}
0.1 \\
0.9
\end{bmatrix}
$$

**What this means:**
Bias adds a constant shift to the neuron output.
Same push from inputs, but the whole output moves up.

That’s why both neurons increased by about the same amount.

### Why ReLU and Sigmoid behave differently

* **ReLU** cuts off negatives → negative stays 0, positive passes through unchanged.
* **Sigmoid** squashes values → small changes in (z) become soft probability shifts, not jumps.


> Weights decide how inputs matter. Bias decides when the neuron activates. Activation decides how the signal is expressed.

# Summary of Day 7

Today you practiced:

- Manual neuron calculations  
- Weighted sums and activations  
- Loss computation  
- A tiny 2-neuron forward pass  
- Playing with weights & biases to build intuition  

This manual work strengthens your understanding before moving to bigger networks and full backpropagation.

---

<p style="text-align:center; font-size:18px;">
© 2025 Mostafizur Rahman
</p>
